### ISSUE TITLE
Unable to get out of getopt loop

### ISSUE THREAD

**Issue by MasterOfTheTiger** [codythegreat/dss#48]
When I first compile the program (from either v0.3.0 or master), I always get the help screen if I try entering an argument (unless I give it `-v`). I was able to add some code to break the loop causing it, but I am confused about why this affects me and not anyone else. 

I am using Termux on Android 5.1. 

Original code:
```
while ((ch=getopt(argc, argv, "hv"))!=EOF) {
        switch (ch)
        {
        case 'v':
            version();
            return EXIT_SUCCESS;
        case 'h':
            usage(), 
            return EXIT_SUCCESS;
        default:
            usage();
            return EXIT_FAILURE;
        }
    }
```

Basically every time the program has a valid argument, like `./dss sample.txt`, the program runs 'usage()' and returns `1`. 

Working code:
```
while ((ch=getopt(argc, argv, "hv"))!=EOF) {
    if (strcmp(argv[1], "-h") && strcmp(argv[1], "-v")) {
        break;
    } ...
```

**Comment by codythegreat** [comment]
Hello @MasterOfTheTiger thanks for submitting an issue. I took a little bit of time off to focus on other projects, so sorry for the delay in response.

This is a weird issue indeed. Maybe this is due to using termux on android? Or perhaps I'll need to look further into android's C implementation? Not sure but that might be what is causing the issues.

I'll try to set up a similar environment as yours and see if I can replicate your issue. I'll add any updates here.

**Comment by amagura** [comment]
I actually use Termux on my smart phone and I'm pretty familiar with `getopt`.  If I have time in the next week or so, I'll see about looking into this.

**Comment by codythegreat** [comment]
@amagura appreciate the help!
